### PR TITLE
open the file for YAML.load

### LINKED ISSUE #30: YAML error loading empty identities file
My `identities.yml` file is empty after being setup by `hector setup`. Here is the stack trace:

<pre>[leedo@trillian lee.hect (master)]$ RUBYLIB=../lib/ ruby ../bin/hector identity remember lee
Enter password: 
/Users/leedo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/psych.rb:297:in `initialize': no implicit conversion from nil to integer (TypeError)
    from /Users/leedo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/psych.rb:297:in `open'
    from /Users/leedo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/psych.rb:297:in `load_file'
    from /Users/leedo/src/hector/lib/hector/yaml_identity_adapter.rb:38:in `load_identities'
    from /Users/leedo/src/hector/lib/hector/yaml_identity_adapter.rb:20:in `remember'</pre>

### PR DESCRIPTION
**Pull request by leedo**
looks to be related to https://bugs.ruby-lang.org/issues/6487
fixes gh-30

### CODE REVIEW

File: lib/hector/yaml_identity_adapter.rb [hunk 1]
```diff
@@ -35,7 +35,7 @@ def normalize(username)
     protected
       def load_identities
         ensure_file_exists
-        YAML.load_file(filename) || {}
+        YAML.load(File.open(filename, "r")) || {}
```
Comment (raws) [inline lib/hector/yaml_identity_adapter.rb]: Does `YAML.load(io)` close `io` after reading from it? Even if it does, we should make sure that happens:

``` ruby
def load_identities
  ensure_file_exists
  File.open(filename, "r") do |io|
    YAML.load(io)
  end
end
```

**Comment by raws** [comment]
Thanks, Lee!
